### ISSUE TITLE
定时任务执行过程中，update_by被修改为0，有什么办法不修改该字段吗

### ISSUE THREAD

**Issue by 18285160741** [zuihou/lamp-job#1]
多租户 定时任务执行时，update_by字段会被修改为0 、有没有什么办法让这个字段不被修该呢？
有劳指点迷津，谢谢

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/112414538-2ceaea80-8d5d-11eb-8258-2f2f9b863437.png)


想办法修改这里的判断或者 ContextUtil.setUserId( null )
