### ISSUE TITLE
lamp-job-master Maven部分依赖无法解析

### ISSUE THREAD

**Issue by 923508946** [zuihou/lamp-job#3]
lamp-cloud-java17

<img width="960" alt="474a2793a4642f0d0902b03a918816d" src="https://github.com/zuihou/lamp-job/assets/75707148/aa74e04b-434d-439f-ac84-27ca6c3729fc">

**Comment by zuihou** [comment]
1， 先编译 lamp-util
2， 编译lamp-cloud
3. 编译lamp-job

```
mvn clean install 
```

**Comment by zuihou** [comment]
lamp-job 依赖了util和cloud项目

**Comment by 923508946** [comment]
都编译过了，主项目已经可以完美启动并且写了一个接口了。


> 1， 先编译 lamp-util 2， 编译lamp-cloud 3. 编译lamp-job
> 
> ```
> mvn clean install 
> ```

**Comment by zuihou** [comment]
分支不对

**Comment by 923508946** [comment]
> 分支不对

![image](https://github.com/zuihou/lamp-job/assets/75707148/efbe3d20-b09e-431e-a4b9-5c227bc3f97b)
![image](https://github.com/zuihou/lamp-job/assets/75707148/bf64e0d2-7eed-4daa-92ba-9711a25c9eb3)

这两个分支无法匹配吗

**Comment by zuihou** [comment]
不对应


lamp-job main 对应 lamp-cloud master  使用jdk8
lamp-job 4.x_java17 对应 lamp-cloud 4.x_java17 使用jdk17

**Comment by 923508946** [comment]
那就是 lamp-cloud 3.x_java17  没有对应的lamp-job啊......
![webwxgetmsgimg (4)](https://github.com/zuihou/lamp-job/assets/75707148/8299d113-a456-43bc-84d4-65995787c76a)

**Comment by zuihou** [comment]
自己基于main 改一下，应该就改几个pom里面的版本和jdk，还有一些import
